apiVersion: v1
kind: episode
metadata:
  name: episode1
  labels:
    block: "no"
    date: Mon, 21 Dec 2020 21:28:38 +0000
    episode: "1"
    explicit: "no"
    guid: c37c40bd94b2
    parent_guid: 0ef9452091ea
    season: "1"
    type: Full
description:
  title: abcd - Episode Title
  summary: abcd - Episode Subtitle or short summary
  episodeText: A long-form description of the episode with notes etc.
  link:
    uri: https://podops.dev/s/abcd/episode1
  duration: 0
image:
  uri: https://cdn.podops.dev/abcd/c37c40bd94b2/coverart.png
  rel: external
enclosure:
  uri: https://cdn.podops.dev/abcd/c37c40bd94b2/episode1.mp3
  rel: external
  type: audio/mpeg
