name: build_cli

on:
  push:
    branches: [ main ]

env:
  VERSION: 0.9.6
  TARGET: cli-0.9.6
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - uses: actions/checkout@v2

    - name: get dependencies
      run: cd cmd/cli && go get -v -t -d ./...

    - name: build cli
      run: |
        mkdir $TARGET
        cd cmd/cli
        GOOS=linux GOARCH=amd64 go build po.go && chmod +x po && gzip po && mv po.gz ../../$TARGET/po-linux-$VERSION
        GOOS=darwin GOARCH=amd64 go build po.go && chmod +x po && gzip po && mv po.gz ../../$TARGET/po-mac-$VERSION
        GOOS=windows GOARCH=amd64 go build po.go && gzip po.exe && mv po.exe.gz ../../$TARGET/po-win-$VERSION
        
    - name: prepare release
      run: |
        echo "$VERSION-$GITHUB_SHA" > $TARGET/version.txt

    - name: setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: upload archives
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: $TARGET
        destination: ${{ secrets.CLI_DOWNLOAD_BUCKET }} 